### ISSUE TITLE
Thrown objects storing all data in EventVariable

### ISSUE THREAD

**Issue by KroFunk** [KroFunk/CandyStats#1]
Misc and XYZ are not being stored correctly.

**Comment by Naiboss** [comment]
When you throw a flashbang, it also has an "entindex" so you can identify which flashbangs blinded which people... we will need to track this.  Store in misc?

**Comment by KroFunk** [comment]
"!== false" had been commented out - This prevented the string from being parsed. Issue Resolved. 

![image](https://user-images.githubusercontent.com/3897442/48849766-fa044680-ed9e-11e8-8041-e502ff5e50fe.png)
