### ISSUE TITLE
GOTV Bot seen as player.  Causes error when uploading log

### ISSUE THREAD

**Issue by Naiboss** [KroFunk/CandyStats#12]
[CandyStats] Reading line:L 12/10/2017 - 10:37:39: "GOTV<2><BOT><>" entered the game
SessionID:l188_039_040_013_27015_201712101037_000.log
[CandyStats] Extracting Timestamp...
TIMESTAMP:2017-12-10 10:37:39
[CandyStats] Extracting Name...
[CandyStats] Is this a player: True
Name:GOTV
[CandyStats] Extracting SteamID...
[CandyStats] Active Players Array updated!
[CandyStats] Prepping MySQL Command...

Error:
( ! ) Notice: Undefined index: $queryString in C:\wamp64\www\CandyStats\upload\ajax_multi_upload.php on line 65
--
1 | 0.0034 | 410712 | {main}(  ) | ...\ajax_multi_upload.php:0
2 | 0.0266 | 486720 | PlayerActive(  ) | ...\ajax_multi_upload.php:226

C:\wamp64\www\CandyStats\upload\ajax_multi_upload.php:69:
array (size=1)
  0 => string 'GOTV' (length=4)

SteamID:GOTV
[CandyStats] Extracting Team...
Team:
[CandyStats] Extracting EventType...
EventType:entered the game
[CandyStats] Extracting EventVariable & Misc Data...
EventVariable:
[CandyStats] Extracting XYZ...
XYZ_1:
[CandyStats] Prepping MySQL Command...

**Comment by KroFunk** [comment]
...I think this has been fixed. I will check in on it.

**Comment by KroFunk** [comment]
GOTV line is being processed correctly, querystring is being populated properly...warning is saying the the string doesn't exist... copy and past the variable into a var_dump (to make sure it's not a typo issue) and it's fine.

I have suppressed the error for now.
