### ISSUE TITLE
Headshots and Other shots are back to front

### ISSUE THREAD

**Issue by KroFunk** [KroFunk/CandyStats#16]
The bar graph legend is the opposite of data shown. I suspect the legend was updated without updating the graph data. 

![image](https://user-images.githubusercontent.com/3897442/54074495-e1a33380-428a-11e9-867a-a1498ca85928.png)

**Comment by Naiboss** [comment]
The chart looks like it might be more broken than that... I don't think it's counting "penetrated" shots. Not sure about multi-status kills but I'd imagine it's not counting them either.

**Comment by Naiboss** [comment]
Fix headshots/other shot... I'll start a new issue for the missing kills
