### ISSUE TITLE
Weapon chart not logging "penetrated" or "headshot penetrated" kills

### ISSUE THREAD

**Issue by Naiboss** [KroFunk/CandyStats#17]
As the title suggests; while the chart is tracking "headshot" kills and "Kill_Base" kills, it isn't tracking any others leading to the numbers being incorrect

**Comment by KroFunk** [comment]
Added additional criteria to weaponbar.php in [04a1733](https://github.com/KroFunk/CandyStats/commit/04a1733b110ce4572aa7363906c076a2b8bfe673)

Regular penetrated kills are recognised as 'Other' and Pen Headshots are 'Headshots'.
