### ISSUE TITLE
Victim list in PlayerStats.php broken for some players

### ISSUE THREAD

**Issue by Naiboss** [KroFunk/CandyStats#18]
On the data I'm using, you receive an error when clicking on the following players: Naiboss, Krofunk, SFA IGamer; relating to the victim list.  All other players seem to work ok...

Error: DataTables warning: table id=globalLeaderboardTEST - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

Let me know if you need the log files

**Comment by KroFunk** [comment]
Chances are that this error was caused by the WAMP implementation on your machine. @Naiboss can you provide the JSON response for analysis?

**Comment by Naiboss** [comment]
Issue was the infinite icon code putting "infinite" in a number field.  Robin has added code to negate this.
