### ISSUE TITLE
Player number changes

### ISSUE THREAD

**Issue by Naiboss** [KroFunk/CandyStats#5]
When a player disconnects and reconnects, their player number will change (understandably) but this means that the EventVariable is different when someone is killed.

Ideally we need to log the STEAM ID of victims in a separate field.

**Comment by KroFunk** [comment]
Player SteamName and SteamID are now stored separately. 

SteamID should be treated as the primary identifier. 
![image](https://user-images.githubusercontent.com/3897442/48857534-0396aa00-edb1-11e8-9445-3b393478165a.png)

BOTs obviously do not have a SteamID, they will be identified by their name followed by <BOT>
![image](https://user-images.githubusercontent.com/3897442/48857916-fb8b3a00-edb1-11e8-931e-080890bff652.png)
